In [19]:
import numpy as np
arr1= np.array([[[7,9,5],
                [6,9,8],
                [4,5,2]]])
print(arr1.shape)
print(arr1.size)
print(arr1.ndim)
print(arr1.base)
print(arr1.strides)
print(arr1.nbytes)
print(arr1.real)
print(arr1.imag)
print(arr1.itemsize)
print(arr1.flags)
print(arr1.T)
print(arr1.data)






(1, 3, 3)
9
3
None
(36, 12, 4)
36
[[[7 9 5]
  [6 9 8]
  [4 5 2]]]
[[[0 0 0]
  [0 0 0]
  [0 0 0]]]
4
  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

[[[7]
  [6]
  [4]]

 [[9]
  [9]
  [5]]

 [[5]
  [8]
  [2]]]
